languageCode = "en"
languageName = "English"
weight = 1
title = "Megan E. Barnes"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "This is a website for Ph.D. student Megan E. Barnes"

[author]
name = "Megan E. Barnes"
image = "barnesprofesh.png"
headline = "I'm Megan Barnes, a Ph.D. student at the <a href = \"lt.unt.edu\"> University of North Texas</a>, studying learning technologies. Join me on this journey as I grow as an academic, and share my excitement for technology, research, and the human side of technology with the world.</h2>"
links = []
bio = "By day, Megan E. Barnes is an educational technology director and elementary school library. When the school day is done, she because Megan E. Barnes, Ph.D. student at the University of North Texas studying learning technologies."
