languageCode = "en"
languageName = "English"
weight = 1
title = "Megan E. Barnes"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Megan E. Barnes"
bio = "I’m Megan Barnes, a Ph.D. student at the University of North Texas, studying learning technologies. Join me on this journey as I grow as an academic, and share my excitement for technology, research, and the human side of technology with the world."
