languageCode = "en"
languageName = "English"
weight = 1
title = "Megan E. Barnes"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "This is a website for Ph.D. student Megan E. Barnes"

[author]
name = "Megan E. Barnes"
