disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Megan E. Barnes"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Megan E. Barnes"
image = "barnesprofesh_hu550921b8d2073e82ad4edb969dac0b1f_717393_192x192_fill_box_center_3.png"
bio = "Megan E. Barnes is a Ph.D. student in the learning technologies department at the University of North Texas. "
