[[main]]
none = "none"

[[main]]
name = "CV"
pageRef = "cv"
identifier = "BzDOMbjRbZ"
weight = 9_999

[[main]]
name = "Creative Projects"
pageRef = "projects"
identifier = "ZhYccHtvhS"
weight = 9_999

[[main]]
name = "Research"
pageRef = "research"
identifier = "GdrdyZuJAQ"
weight = 9_999

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "v3ciWYJHyh"
weight = 9_999

[[footer]]
none = "none"
