[[main]]
name = "Blog"
pageRef = "/posts"
weight = 10

[[main]]
name = "CV"
pageRef = "/cv"
weight = 20

[[main]]
name = "Research"
pageRef = "/research"
weight = 20

[[main]]
name = "Projects"
pageRef = "/projects"
weight = 20

[[main]]
name = "Portfolio"
pageRef = "/portfolio"
weight = 20

[[main]]
name = "Home"
pageRef = "index"
identifier = "UBhtYXpaOh"
weight = 9999

[[footer]]
none = "none"
