
[[main]]
name = "CV"
pre = "wand-magic-sparkles"
pageRef = "CV"
identifier = "q5IhzDxoj8"
weight = 1

[[main]]
name = "Research"
pre = "pencil"
pageRef = "research"
identifier = "G2mvCSTrwJ"
weight = 2

[[main]]
name = "Projects"
pre = "codepen"
pageRef = "Projects"
identifier = "FtOKLjBBbD"
weight = 4

[[main]]
name = "Portfolio"
pageRef = "portfolio"
identifier = "GBvdpEHICe"
weight = 3

[[main]]
name = "Blog"
pre = "hashnode"
pageRef = "posts"
identifier = "QLeGfmwGZB"
weight = 5

[[footer]]
