[[main]]
name = "Blog"
pageRef = "/posts"
weight = 6

[[main]]
name = "CV"
pageRef = "/cv"
weight = 2

[[main]]
name = "Research"
pageRef = "/research"
weight = 5

[[main]]
name = "Projects"
pageRef = "/projects"
weight = 4

[[main]]
name = "Portfolio"
pageRef = "/portfolio"
weight = 3

[[main]]
name = "Home"
pageRef = "index"
identifier = "UBhtYXpaOh"
weight = 1

[[footer]]
none = "none"
