[[main]]
none = "none"

[[main]]
name = "Portfolio"
pageRef = "Portfolio"
identifier = "sYDsd7AnDM"
weight = 4

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "gEQq9ULrqe"
weight = 3

[[main]]
name = "Research"
pageRef = "research"
identifier = "amj520fzmp"
weight = 2

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "zl2aiorYBp"
weight = 5

[[main]]
name = "CV"
pageRef = "cv"
identifier = "6MYepX4uhq"
weight = 1

[[footer]]
none = "none"
