[[main]]
name = "CV"
pageRef = "cv"
identifier = "BzDOMbjRbZ"
weight = 2

[[main]]
name = "Research"
pageRef = "research"
identifier = "GdrdyZuJAQ"
weight = 3

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "v3ciWYJHyh"
weight = 5

[[main]]
name = "Creative Works"
pageRef = "Creative Works"
identifier = "CPtnwPFWjA"
weight = 4

[[main]]
name = "About Me"
pageRef = "/aboutme/"
identifier = "HFHEcrYg6d"
weight = 1

[[footer]]
