[[main]]
name = "Blog"
pageRef = "/posts"
weight = 5

[[main]]
name = "Research"
pageRef = "/research"
weight = 4

[[main]]
name = "Projects"
pageRef = "/projects"
weight = 3

[[main]]
name = "Portfolio"
pageRef = "/portfolio"
weight = 2

[[footer]]
none = "none"
