[[main]]
name = "Blog"
pageRef = "/posts"
weight = 5

[[main]]
name = "Research"
pageRef = "/research.md"
weight = 4

[[main]]
name = "Projects"
pageRef = "/projects.md"
weight = 3

[[main]]
name = "Portfolio"
pageRef = "/portfolio"
weight = 2

[[main]]
name = "CV"
pageRef = "/cv.md"
weight = 6

[[footer]]
none = "none"
