colorScheme = "autumn"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = "enable"
smartTOC = "enable"

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = "show"
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = "enable"
showRecentItems = "5"
showMoreLink = "enable"
showMoreLinkDest = "/posts"
cardView = "disable"
cardViewScreenWidth = "enable"
layoutBackgroundBlur = false

[article]
showDate = "show"
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = "show"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = "show"
showTaxonomies = "show"
showAuthorsBadges = false
showWordCount = true
showZenMode = "show"
heroStyle = "big"
showRelatedContent = "hide"

[list]
showHero = "show"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = "enable"
cardViewScreenWidth = "enable"
constrainItemsWidth = false
heroStyle = "basic"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = "enable"
cardViewScreenWidth = true
heroStyle = "big"

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
