[build]
command = "hugo --gc --minify"
publish = "public"


[build.environment]
HUGO_VERSION = "0.150.0"
GO_VERSION = "1.24.2"
HUGO_ENABLEGITINFO = "true"
[build.environment]
HUGO_MODULE_REPLACE = "github.com/nunocoracao/blowfish/v2"