
[build.environment]
DART_SASS_VERSION = "1.92.1"
GO_VERSION = "1.25.1"
HUGO_VERSION = "0.150.0"
NODE_VERSION = "22.18.0"
TZ = "Europe/Oslo"


# Uncomment if you use Netlify Functions
 functions = "netlify/functions"

 # Optional: Redirects
 [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

 # Optional: Custom headers
 [[headers]]
   for = "/*"
   [headers.values]
     X-Frame-Options = "DENY"